### ISSUE TITLE
phpMyAdmin

### ISSUE THREAD

**Issue by FancyFane** [rackspace-orchestration-templates/lamp#100]
When installing phpMyAdmin on CentOS there was a dependency error for php70. This is not ideal. 

--> Processing Conflict: php70u-common-7.0.1-1.ius.centos6.x86_64 conflicts php-common < 7.0
--> Finished Dependency Resolution
Error: php70u-common conflicts with php-common-5.3.3-46.el6_6.x86_64
You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles --nodigest

I've resolved this issue by first installing php-mcrypt BEFORE installing phpMyAdmin. Once this was done I was able to install phpMyAdmin with out the issues above. Can we fix the install task for this? I'm not familiar with ansible but I believe I've found the relevant file that needs editing. 

lamp/site-cookbooks/LAMP/files/default/lamp/roles/phpmyadmin/tasks/install.yml

Thanks for your time,
FancyFane

**Comment by chrishultin** [comment]
FancyFane:

We're actually in the process of deprecating and removing this template.  Please use LAMP "Production", the repository for which can be found here:
https://github.com/rackspace-orchestration-templates/lamp-small

Please let us know if you have any questions or issues.
Thanks,
Chris H.
