### ISSUE TITLE
Update Icons

### ISSUE THREAD

**Issue by Linuturk** [rackspace-orchestration-templates/lamp#62]
Update the icons for this template.

![lamp_icon_20 5b7 5d](https://cloud.githubusercontent.com/assets/599062/7501235/3da7b4c0-f3f8-11e4-95d8-47c1154af5f0.png)

![lamp_icon_140 5b13 5d](https://cloud.githubusercontent.com/assets/599062/7501233/35f30b6c-f3f8-11e4-8475-41353f17a034.png)

**Comment by rillip3** [comment]
Justin I think this was already done, can you confirm?

**Comment by Linuturk** [comment]
Nope, I'm still showing the old icons in my control panel. These have to be uploaded to the appropriate cloud files account, and the links need to be updated. I'll get this done today.

**Comment by Linuturk** [comment]
Icons have been updated in Cloud Files. CDN will eventually purge and show the new icons.
