### ISSUE TITLE
Failure or hung on RHEL 6.6

### ISSUE THREAD

**Issue by tbr0** [rackspace-orchestration-templates/lamp#63]
Excerpt when running "ansible-playbook -i hosts site.yml -vvvv". Seems to get hung at installing httpd.
```
TASK: [apache2 | install httpd for RHEL based] ******************************** 
<127.0.0.1> REMOTE_MODULE yum pkg=httpd,mod_ssl state=installed
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1430961113.94-212046129352390 && echo $HOME/.ansible/tmp/ansible-tmp-1430961113.94-212046129352390']
<127.0.0.1> PUT /tmp/tmpWl025R TO /root/.ansible/tmp/ansible-tmp-1430961113.94-212046129352390/yum
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python -tt /root/.ansible/tmp/ansible-tmp-1430961113.94-212046129352390/yum; rm -rf /root/.ansible/tmp/ansible-tmp-1430961113.94-212046129352390/ >/dev/null 2>&1']
```
Possible that it succeeds but just takes a long time compared to other OS's. Need to revisit this when I have more time to test. I waited a solid 10 minutes, and no movement from this task. Ended up control-c and installing things manually.

**Comment by tbr0** [comment]
Possible that it succeeds but just takes a long time compared to other OS's. Need to revisit this when I have more time to test.

**Comment by rillip3** [comment]
RHEL is known to take a long time. Currently it takes us almost an hour to complete one because of how slow the yum commands are. Continuous testing is done to ensure they complete, but at this time there's not a known solution, other than to not offer these distros.
